### ISSUE TITLE
Watch's now playing screen does not inform the user of playback errors

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#1030]
### Description

When initiating playback, the Now Playing screen does not show any errors to the user. Instead, it just flips the pause icon back to a play icon when the error occurs. We do show errors [on the episode details and list screens](https://github.com/Automattic/pocket-casts-android/pull/1025). 

It would be good to display some kind of error message that users don't have to find if they are on the Now Playing screen. Some possibilities include a toast (but the user would have to be looking at the watch), a blocking dialog (maybe too heavy handed), or a notification.

### Step-by-step reproduction instructions

1. Install the watch app on a device without an internet connection
2. Attempt to play an episode that is not downloaded from the Episode details or Now Playing screens
3. Observe that once the playback errors, it just reverts the play/pause icon to be a play icon, and no error information is displayed to the user on this screen
4. Observe that there is error information on the Episode details and episode list screens from #1025 

### Screenshots or screen recording

Note that I trimmed the middle of this clip to keep it shorter. I actually had to wait 20 seconds or so for the playback to fail.

https://github.com/Automattic/pocket-casts-android/assets/4656348/32cd50a5-1aca-4a37-ac7f-63c2cbd5b8f1

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Wear 3 emulator running a 7.40 pre-release build.

**Comment by atharv028** [comment]
Hey @mchowning, I was thinking of adding an indicator (something like an exclamation mark) inside the play button itself to notify the user that some error has occurred and when the user clicks on the button, we can do either of these two things : 

1. Navigate the user to Episode detail screen, where the cause of the error is displayed (as you mentioned this is already implemented in #1025)
2. Implement a retry mechanism to try and play the episode again.

Otherwise, we can do a combination of these things, something like "if the episode throws error, when the user clicks on play button (which is now error button), retry for 2-3 times before showing him the error screen/episode screen with error details" 

## Screenshot for sample error button

![Screenshot_2023-06-07-13-48-03-71_b783bf344239542886fee7b48fa4b892](https://github.com/Automattic/pocket-casts-android/assets/89896473/9acd05bf-d347-44c7-a69c-3945797e8b99)

**Comment by mchowning** [comment]
Do you have any thoughts on the best UI/UX to use on the Now Playing screen when there is a playback error @david-gonzalez-a8c ?

**Comment by mchowning** [comment]
@david-gonzalez-a8c has suggested going with a lighter approach, and just adding an icon before the title to indicate an error like this.

![image](https://github.com/Automattic/pocket-casts-android/assets/4656348/639cc564-cf16-4d4a-a023-905df5269153)


Tapping on that would take the user to the episode details screen like it does now where the full error is displayed.

<details><summary>icon svg</summary>

``` xml
<svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
<circle cx="8" cy="8" r="8" fill="white"/>
<rect x="7" y="3" width="2" height="6" rx="1" fill="black"/>
<rect x="7" y="11" width="2" height="2" rx="1" fill="black"/>
</svg>
```

</details>

I think it also could be worth having the watch lightly vibrate to alert the user that there has been a playback error. Doing that vibration without a corresponding notification may be confusing though, so maybe we should hold off on that for now. I do think that adding a full-blown notification might be the right next step for this, but let's hold off on that until we get a better idea for how much trouble  our users are having with playback errors.

Feel free to pick this up if you're still interested in working on it @atharv028 ! 🙇
