### ISSUE TITLE
Watch: Add a way to access logs and contact support

### ISSUE THREAD

**Issue by mchowning** [Automattic/pocket-casts-android#1069]
### What problem does this address?

There is no way for a user of the watch app to contact support and send their logs.

### What is your proposed solution?

We should add an ability to "share" the logs with support via email.

### Did you search for existing feature suggestions?

- [X] I have searched for existing feature suggestions.

**Comment by atharv028** [comment]
Hey @mchowning, I think adding a button to report/share such issues in the watch can be helpful, something along the lines of "Report a bug". 

<img src="https://github.com/Automattic/pocket-casts-android/assets/89896473/e4693b10-a5c9-4b10-8f4c-417b5458d5a9" width="40%" height="40%">

The normal flow for the phone as I saw in #911 and #950 is that we are opening an email app with logs attached for plus users and redirecting to forum for free users.

Since the app can only be used with plus account, we only need to take care of those users.

The first and easiest approach which comes to my mind since we cannot use any email app intuitively on watch, is to do a network request (POST) to the backend and share the following information :-

1. Error/bug faced by the user (we can show a input box to the user to enter the issue/error they are facing)
2. The log file contained within the app
3. (Optional) The logged in user's mail (as to provide a confirmation mail)

What do you think?

**Comment by mchowning** [comment]
What you're suggesting makes sense @atharv028 , and we've actually been doing a bit on sending encrypted logs directly from the ap already, but that's not ready yet so I think the better immediate solution is to just send the logs from the watch to the phone app and then the phone app can email/share them appropriately. I'm working on implementing that currently.

**Comment by atharv028** [comment]
ah I see. I was too focused on sending the logs directly from the watch app.

**Comment by mchowning** [comment]
This was addressed by #1088
