### ISSUE TITLE
Duplicate app icon during pride month

### ISSUE THREAD

**Issue by nonsenseninja** [Automattic/pocket-casts-android#1098]
### Description

Hi,
when the rainbow app icon showed up (great cause but looks irritating on my home screen) I tried to change it. Setting any other icon will cause two instances of Pocket Casts to reside in the app drawer. One rainbow, one of your choosing.

### Step-by-step reproduction instructions

Go to settings and change the app icon to anything other than "Pride 2023".

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 6a, Android 13 build TQ2A.230505.002, Pocket Casts 7.40 (9104)

**Comment by CookieyedCodes** [comment]
They are quite clear two icons would appear if the default icon is changed, the icon will change back to default at the end of the month, if it's still going to be an issue I would recommend you install an icon pack & change the icon or just deal with the icon for a few weeks.

Pockecasts team are aware of the issue & from what I've heard it's an Android limitation if you can provide proof otherwise from another open source app that allows icons to be changed in app that would be greatly appreciated for future years tho 😁.
Not a pockecasts employee just solving your issue 😅 

![Screenshot_2023-06-17-17-34-12-53_28ad70af3b47247953fcd94176b9a9c1.jpg](https://github.com/Automattic/pocket-casts-android/assets/20846898/e46e1b4f-26b5-4001-9b63-20cb3a718044)

**Comment by nonsenseninja** [comment]
> They are quite clear two icons would appear if the default icon is changed
Wow. I am so embarassed right now but my brain totally skipped over that part while reading the message. My bad.

**Comment by MtndaleRedneck** [comment]
> They are quite clear two icons would appear if the default icon is changed, the icon will change back to default at the end of the month, if it's still going to be an issue I would recommend you install an icon pack & change the icon or just deal with the icon for a few weeks.
> 
> Pockecasts team are aware of the issue & from what I've heard it's an Android limitation if you can provide proof otherwise from another open source app that allows icons to be changed in app that would be greatly appreciated for future years tho 😁.
> Not a pockecasts employee just solving your issue 😅 
> 
> ![Screenshot_2023-06-17-17-34-12-53_28ad70af3b47247953fcd94176b9a9c1.jpg](https://github.com/Automattic/pocket-casts-android/assets/20846898/e46e1b4f-26b5-4001-9b63-20cb3a718044)
> 
> 

In Overcast you can change the default icon and it doesn't duplicate it

**Comment by CookieyedCodes** [comment]
Isn't overcast an iOS exclusive app, this is not an issue with pockecasts on ios

**Comment by nonsenseninja** [comment]
Overcast is indeed an iOS-only app and not open source.

**Comment by MtndaleRedneck** [comment]
Sorry. Meant Overdrop. https://play.google.com/store/apps/details?id=widget.dd.com.overdrop.free

**Comment by CookieyedCodes** [comment]
> Sorry. Meant Overdrop. https://play.google.com/store/apps/details?id=widget.dd.com.overdrop.free

Care to provide a GitHub link if it's open source?

**Comment by MtndaleRedneck** [comment]
> > Sorry. Meant Overdrop. https://play.google.com/store/apps/details?id=widget.dd.com.overdrop.free
> 
> Care to provide a GitHub link if it's open source?

🤷‍♂️ No idea if it's open source. But it's allowed you to change the default icon for at least a year that I know of.

**Comment by CookieyedCodes** [comment]
Fair enough, I just want to make it easy for them to fix it that be all 😉
