### ISSUE TITLE
Playback skips back a half-second, once, every playback, about 30 seconds in

### ISSUE THREAD

**Issue by jamescridland** [Automattic/pocket-casts-android#1491]
### Description

When playing back a podcast on PocketCasts, the app repeats about half a second of the podcast. This happens consistently for every podcast, about 30 seconds or so into the podcast (the exact time differs).

> If you want to know what it sounds like, it sounds a little like little like this.

This occurs on _every_ podcast, whether it has dynamic advertising or not.

### Step-by-step reproduction instructions

1. Have playback speed set to 1.3x // trim silence set to "Mad Max" // volume boost set on
2. Do NOT auto-download the podcast
3. Find an episode to listen to, and press play. After a short time listening to the podcast, it will skip slightly backwards, and you'll hear a word or two repeated.

This is 100% reproducible, as above. It does NOT happen when an episode has been auto-downloaded.

What I think is happening is this: when you hit play, PocketCasts 'streams' the audio file, but also starts downloading a copy of the audio file to storage. When it has finished downloading it - which for my cell network takes about 30 seconds - it switches state from 'streaming' the audio file, to playing the audio file back from the download. However, it has failed to take into account the time saved by trimming silence (or maybe playback speed), and starts playing the downloaded file at the wrong place. It results in a second or two being repeated (and it might well be the case that this is the total amount of audio skipped in trim silence).

It's happened for the last three years of using PocketCasts on my Android phone; and it's only now that I've thought it might be worth reporting this as a bug.

(Interestingly, during a podcast with dynamically-inserted preroll ads, you can hear the skip happening within the ad.)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel, with Android 12/13/14, and all recent Pocket Casts versions.

But, specifically for today, Google Pixel 6 Pro, Android 14, Pocket Casts version 7.50-rc-1 (9157)

**Comment by CookieyedCodes** [comment]
They are aware of the dynamic ad issue & they are kind of looking at fixing it, it dosent happen to downloaded files keeping dynamic ad tech from changeing stream unpause to steam unpause is the issue 😅, 

regarding the vast majority of this issue why this hitch mainly happens tho it's because the streamed podcast are switching to downloaded episode + the hitch is a bit unavoidable probably for verification purposes & also people noticing the gap because of the the switch & pause I
In that gap to switch but can it be shrunk I wonder 🤔-at that PC is probably slightly lessing the number of ping tracks on a stream just to cut down on fees a bit because I'd say it's one of their bigger expenses 😅-

**Comment by jamescridland** [comment]
> They are aware of the dynamic ad issue & they are kind of looking at fixing i

This is **not an issue with dynamic ads.** It happens for every podcast, irrespective of the content of the podcast.

> the streamed podcast are switching to downloaded episode + the hitch is a bit unavoidable probably for verification purposes

I've no idea what you mean by "verification purposes". The switch is entirely avoidable - it just needs to correctly load the downloaded copy at the right time.

> I wonder 🤔-at that PC is probably slightly lessing the number of ping tracks on a stream just to cut down on fees a bit because I'd say it's one of their bigger expenses

There is no expense to PocketCasts if my app listens to a show on the internet. The audio files are directly requested by my app and the podcast hosting company, and does not go via PocketCasts servers.

**Comment by CookieyedCodes** [comment]
1. Yes but I am makeing you aware of that the dynamic ad issue is a seperate one 

2.The switch is the verification 

3. Yes the audio files are not pocketcasts but pocketcasts is doing live tracking to make the switch as seemless as possible that ping is the expense & more pings on playback means more expense, tbc I'm not saying that it can't be closed or fixed but theirs likely a reason & a Dev could give better clarity on 😅

**Comment by jamescridland** [comment]
@CookieyedCodes Thanks. I still don't understand "the verification", and PocketCasts makes *no* "pings" on playback to the podcast host. Zero. None. I appreciate you're trying to help.

**Comment by jamescridland** [comment]
@CookieyedCodes I'm a bit unclear why you're commenting here, given you don't appear to understand the issue, nor understand how Pocket Casts works. Do you think - asking nicely - you could butt out of this bug report? You're just adding noise.

**Comment by CookieyedCodes** [comment]
Ya no bothers, I'd disagree in not understanding the issue tho tbc, I'm just trying to explain why it might be a hard fix/why it's the case, agree completely that it should be better 😄

**Comment by yaelirub** [comment]
Hey @jamescridland , thanks for reporting! We are looking into this issue and will report back here with our findings and a possible fix.
Yael (Ellie) Rubinstein, Head of Pocket Casts

**Comment by mchowning** [comment]
👋 @jamescridland , I believe we've got a fix for this issue in #1510. 

I don't think the issue was caused by any of the playback effects like trim silence. Instead, I think that what is happening is that when we switch from streaming the episode to playing back the downloaded episode the app was just restoring a slightly out-of-date playback position. I expect to have this fix in the `7.52`. 

> ### Step-by-step reproduction instructions
> ...
> 2. Do NOT auto-download the podcast
>
> What I think is happening is this: when you hit play, PocketCasts 'streams' the audio file, but also starts downloading a copy of the audio file to storage.

The app doesn't download episodes that are being streamed unless one of the auto-download settings is turned on. Do you perhaps have the setting for auto-downloading episodes added to the Up Next queue turned on? That would cause any episode you start playing to get downloaded since it gets added to the Up Next queue when it starts playing, and would cause the skip back issue. 

Without having one of the auto-download settings turned on and just streaming an episode, I couldn't recreate the skip back you described. If I had the app auto-download episodes added to the up next queue though, I saw precisely the behavior you described, and that is fixed by the changes in #1510.

**Comment by jamescridland** [comment]
> Do you perhaps have the setting for auto-downloading episodes added to the Up Next queue turned on?

Yes. That was it! :)

Thank you. Excellent. Very pleased to hear it.
