### ISSUE TITLE
Fix change email handling

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#1511]
### Description

When a user navigates away from the `Change Email Address` screen while `/user/change_email` request is in progress, HTTP failed error is received and the new email address is not reflected in the app even though it gets changed on the server. It is not updated even after a forced refresh. The only way to see the new email is to log out and log in with the new email.

Failed response:
```
 I  --> POST https://api.pocketcasts.com/user/change_email
 I  Content-Type: application/json; charset=UTF-8
 I  Content-Length: 86
 I  Authorization: Bearer ACCESS_TOKEN
 I  {"email":"xxx@automattic.com","password":"xxx","scope":"mobile"}
 I  --> END POST (86-byte body)
 I  <-- HTTP FAILED: java.io.IOException: Canceled
```

### Reproduce behavior when email change is not reflected in the app

1. Login with an email address
2. Go to `Profile` -> `Account`
3. On the `Pocket Casts Account` screen, tap `Change email address`
4. On the `Change Email Address` screen, enter new email and confirm password
5. Tap `Confirm`
6. Quickly navigate away from the screen while the request is in progress
7. Notice that on the `Pocket Casts Account` screen, the email address is still the old one
8. On the `Profile` tab, tap `Refresh now`
9. Go back to `Pocket Casts Account` screen by tapping `Account` button on `Profile` tab
10. Notice that the email address is still the old one 

### Check if the email address is changed

11. Continue from above
12. Logout
13. Login with the new email address
14. Notice that the login is successful and the account has all data from the previous account confirming that the change email request was completed on the server 

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by suwasto** [comment]
In my testing, it seems that the ```disposables.clear()``` inside ```onCleared()```  in the ```ChangeEmailViewModel``` called so that the network request cancelled by client. the request already accepted and processed by server but the response lost due cancelation of http request on disposable cleared. Since we don't have any other network request in the ```ChangeEmailViewModel```  other than ```changeEmail()``` function, how about we remove ```disposable.clear()``` inside ```onCleared()``` method and move it after the request finished ex: ```doOnSuccess``` and ```subscribeBy(onError{})``` ?, will it cause memory leaks?

Another alternative I can think of is move the changeEmail to the activity view model ```AccountActivity``` so that the request is not canceled on navigate away from ```ChangeEmailFragment```
