### ISSUE TITLE
Incorrect multiple device sync when an episode is left playing on the last device, completed on another and the app is restarted

### ISSUE THREAD

**Issue by ashiagr** [Automattic/pocket-casts-android#1649]
### Description

The issue was reported for sync between Automotive and the phone app.

When an episode is left playing on the Automotive app, and completed on the phone app, followed by playing another episode on phone app, then on restarting the Automotive app, the last playing episode on the Automotive app continues to play from the last play position instead of switching to the last synced episode from the phone app. 

Moreover, it gets added to the up-next even though it was completed on another device.

This usually happens because if an episode is currently playing on the device, then [episode playedUpto is not updated and the playing status is marked as unsynced](https://github.com/Automattic/pocket-casts-android/blob/main/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/sync/PodcastSyncProcess.kt#L823-L841).

Suggested fix: Add a setting to delay playback on boot until server sync or x secs so that the correct episode is played from its last synced position on another device.

### Step-by-step reproduction instructions

1. Play an episode (Episode A) in Automotive app
3. Open phone app and force sync from the Developer settings
4. Complete the above playing episode (Episode A) in the phone app
5. Play another episode (Episode B) on the phone app
6. Force sync from the Developer settings
7. Restart the automotive app (this force refreshes the app)
8. Notice that the episode (Episode A) continues to play from its last played position even though it was completed on the phone. It does not switch to Episode B which was the last synced episode from the phone app.
9. Refresh the app from Settings in the automotive app
11. Open the phone app
12. Force refresh the app
13. Notice that episode (Episode A) is added to the upnext queue even though it was completed on the phone earlier

According to the user report (7481359-zd-a8c), at step 7, Episode A seeks to Episode B last played up to the position. However, I wasn't able to reproduce it.

### Screenshots or screen recording

https://github.com/Automattic/pocket-casts-android/assets/1405144/612d6874-1849-437c-9155-1315466fde1a

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

7481359-zd-a8c

**Comment by igotdes** [comment]
@ashiagr The user in #7481359-zen has shared a screenshot:

![7481359-zen](https://github.com/Automattic/pocket-casts-android/assets/74066241/dc22944f-7f0f-462e-9cc4-b89570ddf42a)

Their description of what happened is as follows:

> In the attached image the S4E6 The Faith of Flowers is where the car started playing (a previously finished episode). Current episode was S4E12 Beyond the Real. Based on the "time remaining" you can see it synced that episode to the correct spot, but did not transfer over to playing that one

**Comment by joashrajin** [comment]
@ashiagr does this sound related?

> I use the AAOS version in my Volvo and iOS on my iPhone. I start a podcast in the car and want to pick up where I left off on my iPhone, and 99% of the time it seems as though the iPhone does not receive the sync point from the AAOS. I even go in and manually refresh in the volvo before turning it off, and then manually refresh on the iOS before starting. and the episode will show as though it has never been started.

7768194-zd-a8c

**Comment by joashrajin** [comment]
Another one relating to the above comment: 7768201-zd-a8c

**Comment by joashrajin** [comment]
>  love using your app, but same problem for me using AAOS in a Volvo XC40. Any updates in this regard? Thanks!

https://forums.pocketcasts.com/forums/topic/pocketcasts-on-android-automotive-aaos-does-not-sync-reliably/?view=all#post-3268

**Comment by joashrajin** [comment]
https://forums.pocketcasts.com/forums/topic/pocketcasts-on-android-automotive-aaos-does-not-sync-reliably/?view=all#post-3282

**Comment by joashrajin** [comment]
@ashiagr do we have any recommendations or updates for this?

**Comment by igotdes** [comment]
https://forums.pocketcasts.com/forums/topic/pocketcasts-on-android-automotive-aaos-does-not-sync-reliably/?view=all#post-3565

**Comment by igotdes** [comment]
https://forums.pocketcasts.com/forums/topic/pocketcasts-on-android-automotive-aaos-does-not-sync-reliably/page/2/?view=all#post-7098

> Same issue with the Honda Civic with AAOS. I start the car and it starts playing where the car left off, which is not the latest sync was from my phone. If that episode was already completed and archived on my phone it re-adds the episode to my queue at the top.
> 
> So, I then have to hit pause, go to settings, refresh now. Then I have to go to the playlist to select the actual episode I was listening to, which is synced to the right timecode now. Then on my phone I have to remove the episode it re-added from the queue. This is all very awkward.

The workaround we shared to pause the episode before turning off the car did not work for them.

**Comment by connormxy** [comment]
Another example of the same bidirectional failure to sync the listen time. When starting the app in the car, basically does not seem to ever. Lloyd, the most recent /currently played podcast that had been synced from another device at all, let alone sync up to the playtime. 

After leaving the AAOS app, any other Pocket casts client actually does eventually refresh and pull the most recently listened to episode (based on what was just being listened to in the car) to the top of my Up Next queue, but again, all listening history is erased and playback restarts at zero as it appears as if it hasn't been played yet.

This is currently a 2022 Volvo XC60 and a 2025 Volvo EX90. What's a little bit startling and frustrating is that the XC60 just the other week jad a recent upgrade from a significantly earlier version of Android, I think the prior version was still technically Android automotive, And at that time the Pocket casts app behaved dramatically more like I would have expected on my other Android clients from the perspective of specific functionality that Pocket casts provides. General user interface was certainly dated as a result of the Android version itself that was being targeted, but the functionality and experience of the podcast app was more or less intact and it is weirdly broken now. The current version served by the Play store for Android automotive 13, I think, has all of these issues.

Also a feature request, it seems to not have access to the Up Next queue anymore (did have access to this on the prior version), which is also pretty fundamental. While playing a podcast, or from the dashboard on the app, there is no way to open up the Up Next queue. Picking a new podcast has to be done either manually from the podcasts, from suggestions, or from a playlist like In Progress, which sometimes defeats the purpose, or New Releases, which generally gets you close but may not be how your Up Next is set up.

It's very weird how it is clearly a more modern version, but the functionality is kind of drastically different than the version served to older Android tablet/ ?automotive versions.

Unfortunately, the EX90 does not have Android Auto available at this time and so that is not an option; instead the Android automotive is almost at such parity with the modern handhelds, that it would make up for it, but this does kind of defeat the purpose.

I'll try to Re-Engineer some of these scenarios on the starting and the ending of the app, whether I waited or manually refreshed or hit play or hit pause before disconnecting, whether another client is trying to refresh or how long I waited between uses etc. And tried to get you some logs over the next few days. I'll try to describe exactly what situations I triggered. Sorry for a future promise but just wanted pitch in in order to mention a behavior that I wasn't sure I saw mentioned, on my brief skimming, on this issue or on the support chat that is being copied here
