### ISSUE TITLE
Podcast artwork doesn't display with Tesla

### ISSUE THREAD

**Issue by geekygecko** [Automattic/pocket-casts-android#2237]
### Description

When playing an episode through Bluetooth the Tesla media screen does not display the artwork. This is working in the other apps I tested so it must be possible. The other apps were Google Podcasts, Audible, Spotify, and AntennaPod.

Internal reference: p1713956545483609-slack-C02A333D8LQ

### Step-by-step reproduction instructions

1. Connect your Bluetooth to a Tesla 🚗
2. Play an episode
3. See the artwork is not displayed

### Screenshots or screen recording

![20240516_101548](https://github.com/Automattic/pocket-casts-android/assets/308331/37aab9d6-6a40-446b-bb02-16e4395db996)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung Fold5, Pocket Casts 7.54-rc-2

**Comment by P-Burk** [comment]
Just wanted to chime in because I've also experienced this. 

Also, maybe I'm not remembering correctly because I don't pay a lot of attention to it, but I could have sworn that sometimes it works and sometimes it doesn't. It might be podcast specific. But like I said, I can't make a definitive comment on it as I don't really pay it much attention.
