### ISSUE TITLE
"Download Failed - Failed to create a secure connection to the authors's server" for several podcasts

### ISSUE THREAD

**Issue by passy** [Automattic/pocket-casts-android#2569]
### Description

Hello authors of my favourite podcasting app,

for about a month now I've been unable to download certain podcasts that worked before. The error message is "Download Failed - Failed to create a secure connection to the authors's server".

![unnamed](https://github.com/user-attachments/assets/90186dc0-3923-4cd0-90ef-418329e38e08)

This only happens for a specific set of podcasts and only on my "podcast phone" which is an old Xiaomi Mi A1 running Android 9. My Pixel 6 Pro doesn't have any issues downloading the same episodes.

My guess is that this may be due to the Let's Encrypt certificate chain which no longer supports Android < 14 for the ISGR Root X2 but I know that Chrome, for instance, manages to circumvent this by augmenting the system's certificate chain.

Adding the root certificates manually into the system's cert store doesn't seem to help, unfortunately. As an additional (if messy) data point, this probably started around 2 months ago, then worked again for about two weeks, then stopped permanently for about a month now. My sense of time is currently a little warped so maybe apply a factor of 2 to these. I also cannot tell if the episode host changed something on their end or if you potentially shipped a change temporarily in the client.

I couldn't find anything too interesting in logcat. The WorkManager item seems to switch almost immediately from started to `SUCCESS`, to `RETRY`.

This is not specific to any network. I tried my WiFi at home, other people's WiFis, cellular and VPNs.

I'm not sure if this is related to #2287 or not, but given the specific error message about the "secure connection", I assume it's separate.

If there are any other logs or pieces of information that could be useful, please let me know. Thanks!

### Step-by-step reproduction instructions

1. Download one of the following podcasts:

1.1. https://pca.st/pcgvewv0
1.2. https://pca.st/mhnykmes
1.3. https://pca.st/bwofnfsb

2. Notice that episode will get stuck in "Queued" and eventually switch into "Download failed" mode.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

* Xiaomi Mi A1
* Android 9
* PocketCasts 7.68

**Comment by igotdes** [comment]
Also reported by user in #8547931-zen

**Comment by MiSikora** [comment]
@passy Thanks for the report. You're correct that the issue seems related to the certificate provider used by certain podcast servers. Ideally, this should be resolved on their end, but I understand that, from a user's perspective, this distinction doesn't really matter.

That being said, it appears the problem may be getting addressed by the certificate issuer or the podcasters themselves. For example, [this episode](https://pca.st/mhnykmes) that you linked was not downloadable for me a few days ago on older devices, but now it downloads without issue because the host updated their URLs. Additionally, other podcasts still using `media.blubrry.com` are working fine for me now as well.

Could you please check again to see if you're still experiencing the issue?
