### ISSUE TITLE
Details Screen Jumps to the Bottom When Scrolling Down

### ISSUE THREAD

**Issue by thabotswana** [Automattic/pocket-casts-android#2716]
### Description

When you scroll down the Details screen, the app will jump to the bottom. The screen does not scroll down smoothly.  

Reported by a user in 8644805-zd-a8c.

### Step-by-step reproduction instructions

1. Go to the Details screen
2. Scroll down the screen

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Samsung Galaxy S21 Ultra wAndroid 14, Pocket Casts 7.71-rc-2

**Comment by joashrajin** [comment]
To add more info, on my Fold 4, I was able to replicate the issue on certain episodes which have notes which go just over the viewport. Not the easiest to replicate since it depends on the length of the notes

https://github.com/user-attachments/assets/f9b4f85b-5a4d-433f-b039-9a78546ef9ba


In my video, I was looking at https://pca.st/episode/eb5248fc-18ac-43f8-92f2-8be3de184d00

**Comment by aurarora** [comment]
I am experiencing this on my Samsung Galaxy S23FE with Android 14 / OneUI 6.1.

What's happening is, that upon tapping on a text view after it first appeared on screen, that text view is snapping to the top of the screen. After that first snap, as long as it stays on screen, it does not snap anymore.
I will share a few videos below, however, this is not limited to only Pocket Casts. I have also experienced this in other applications such as my E-Mail app (WEB.DE Mail).
I'm unsure whether this might be a general problem that OneUI has with a specific type of text view. (Especially since you are also using a Samsung device @joashrajin)


Screen Recordings Pocket Casts:

https://github.com/user-attachments/assets/1c7ef61c-502b-44d5-b2a5-b803fa8ef5e4

https://github.com/user-attachments/assets/b95f50ac-b216-410e-b1a8-9ec5dda8b72b

https://github.com/user-attachments/assets/02626d30-6a57-49f4-95f9-5beea9e7612e

Screen Recording WEB.DE Mail:

https://github.com/user-attachments/assets/fce59c93-a236-4459-b9ab-9c1639d8b33d

**Comment by thabotswana** [comment]
Another report in https://forums.pocketcasts.com/forums/topic/episode-descriptions-jump-down-instead-of-smoothly-scrolling/?view=all#post-5337

![describe-the-bug-ezgif com-optimize](https://github.com/user-attachments/assets/08ebc289-20cc-4517-b525-3f284ccf7106)
