### ISSUE TITLE
Wear OS version

### ISSUE THREAD

**Issue by yechielw** [Automattic/pocket-casts-android#468]
### What problem does this address?

Currently, there is no way to listen to podcasts when the wear OS watch is not connected to the phone via bluetooth

### What is your proposed solution?

Publishing a trimmed down version of the app targeted for wear OS which will enable the options to stream and Download episodes directly from the watch.

at the moment, none of the big players (besides Spotify) offer a watch version of their podcast app.

### Did you search for existing feature suggestions?

- [X] I have searched for existing feature suggestions.

**Comment by mchowning** [comment]
We have [gotten a start on this](https://github.com/Automattic/pocket-casts-android/tree/add/wear), but it's really just a start. Other priorities are keeping us from spending much time on it at this time. Contributions would be welcome though! 😄

**Comment by Salzian** [comment]
@mchowning Is there some coordination on this effort already? I would love to contribute.

**Comment by mchowning** [comment]
>  I would love to contribute.

That would be great @Salzian ! 

> Is there some coordination on this effort already?

We were mostly coordinating on private channels before now, but going forward this thread is probably the best place to coordinate now that we want to do that publicly (I'm open to other suggestions though).

We're largely looking to replicate the functionality from Pocket Casts' iOS watch app to start—not because we want the WearOS to be exactly the same as the iOS watch app, but more because that seems like the easiest way to create our first iteration for WearOS. You can do an iOS build yourself to explore the watch app on a simulator, but in case you can't (or don't want) to do that, this is what it looks like.

![Apple Watch](https://user-images.githubusercontent.com/4656348/201352755-470b9340-44b3-429d-b6f6-c04210c310be.png)

Our plan was to support offline playback as suggested in https://github.com/Automattic/pocket-casts-android/issues/490.

My inclination would be to focus on the Now-Playing/Up-Next functionality first since that seems like the core functionality. We might even be able to do a release with WearOS support with only that functionality. 🤔  If there's something else you're interested in working on though, feel free to tackle that.

**Comment by Salzian** [comment]
I'm going to review progress on branch `add/wear` first. I agree that for the beginning, we should focus on getting playback working on Wear OS, especially for standalone users.

**Comment by mchowning** [comment]
> Mostly initial setup of the app and the UI layout of it, am I right?

That's right

>  think a first step would be to establish the connection between watch and phone to remotely control playback on the phone.

That makes sense to me. 👍

**Comment by Salzian** [comment]
I'm not aware of Tasker. Is this the preferred way of implementing the Pocket Casts Wear OS experience? That would make this PR / effort obsolete.

**Comment by joaomgcd** [comment]
It is not the preferred way, but it's a DYI way of hacking around it 😁 A native Wear OS app would be much better, but in the meantime you can get it working with Tasker in a more basic/harder way.

**Comment by samueljim** [comment]
I just want to say that i appreciate all you working on this. I just got a pixel watch and i'm so sad there's no app yet. Let me know what i can do to help. I'm only a web dev so my skills are not going to be the most useful. Please let me know if i can lend a hand :)

**Comment by Salzian** [comment]
Small update from me, I wasn't able to dive much into it recently due to work stuff. Hope to have a fresh start into December.

**Comment by krisdb** [comment]
Check out [Wear Casts](https://play.google.com/store/apps/details?id=com.krisdb.wearcasts) on the Play Store if you want to listen to podcasts on your WearOS watch.

**Comment by krisdb** [comment]
Is that going to be the UI? It's atrocious.

**Comment by krisdb** [comment]
The  Tasker + AutoWear works great for me. I don't see a need for a dedicated app.

**Comment by CookieyedCodes** [comment]
@krisdb like sure but it still enhances plus & who knows it might be quicker & easier to do it direct + if it syncs that will definitely save time, 17 people liked this post so it's - # still valued & appricated, I'm all for alternatives but I wouldn't shame development enjoy your app tho ☺️

**Comment by krisdb** [comment]
I'm just saying don't prioritize it over other functionality as there's an option. If there was no option then I'd say but the work in but building for WearOS is not trivial.

**Comment by CookieyedCodes** [comment]
Fair enough, I don't mind them focusing on this it's long requested, what do you want them to be focusing on just interested:)

**Comment by mchowning** [comment]
> what do you want them to be focusing on just interested:)

Let's try to keep this issue focused on WearOS. Feel free to open up a [discussion](https://github.com/Automattic/pocket-casts-android/discussions) on this though.

**Comment by krisdb** [comment]
Another issue is developing for WearOS is annoying. I've made some small utility apps for WearOS and abandoned them because they would get approved then rejected. Google has some weird criteria for WearOS apps and approvals take forever. For example, a WearOS app has to look good on square screens even though there are no WearOS watches that are square. All I am saying is don't get into WearOS if you don't have to. Who knows, Google may abandon it like their other products.

**Comment by keithnet** [comment]
> The Tasker + AutoWear works great for me. I don't see a need for a dedicated app.

Not trying to restart debate here, but correct me if I'm wrong? 
The Tasker solutions doesn't support the ability to use PocketCasts without carrying a phone, does it? This a key overdue feature IMO. Appreciate the work on this very much.

**Comment by NoahAndrews** [comment]
Hey everyone! I might spend some time here and there contributing to the Wear OS app. Tonight, I did some investigation into authentication credentials syncing between the Wear OS app and the Android app (sadly syncing credentials on iOS is not supported).

[Google's official guide](https://developer.android.com/training/wearables/apps/auth-wear#tokens) on this uses the `DataClient` in the Wearable Data Layer API. In my view, that is an extremely questionable choice, given that data stored using the `DataClient` API is synced to Google's servers, as per [this table](https://developer.android.com/training/wearables/data/data-layer#comparison-table) and the "synchronize data" section above it. I think they recommend it for ease of use and optimal user experience (since it makes the data available even if the watch isn't connected to the Android phone via Bluetooth at that particular moment), but it seems to me like a significant security tradeoff.

I believe the best alternative would be to use a `MessageClient` to send over the token via Bluetooth.

For an app like Pocket Casts, having that token stored on Google's servers probably isn't the end of the world, but I hate that the sample code does that. I could totally imagine an app containing much more sensitive data using that mechanism without realizing the implications. Either way, I'd like to get the Pocket Cast's teams opinions on this.

**Comment by NoahAndrews** [comment]
On my Galaxy Watch 5, scrolling performance is terrible with a `debugProd` build, even on the short top-level menu when you're not logged in. When I tried to build a release build, the Gradle task `processReleaseGoogleServices` errors out, which I'm guessing will be a dead end for me as a non Automattic employee (if it matters, I have the #795 branch checked out, which I see seemed to add some Google server related stuff).

Is the scrolling performance good in release mode, or does it need improvement there as well?

**Comment by NoahAndrews** [comment]
I see that horologist has a not-yet-documented Auth Data library, so I started a discussion there as well. Their opinions will probably be valuable: https://github.com/google/horologist/issues/1036

**Comment by krisdb** [comment]
Welcome to WearOS development

**Comment by mchowning** [comment]
👋 @NoahAndrews !

>  I might spend some time here and there contributing to the Wear OS app.

That's fantastic! 🎉  We've actually started more actively developing the watch app this week, so your timing is great! Just let me know if there's anything you'd like to work on so we can coordinate.

> [Google's official guide](https://developer.android.com/training/wearables/apps/auth-wear#tokens) on this uses the DataClient in the Wearable Data Layer API. In my view, that is a very questionable choice...

You make a lot of good points. In the draft PR with an [initial authentication POC](https://github.com/Automattic/pocket-casts-android/pull/801) that I just opened (I had actually already working on it when you left your comment) I decided to use the Data Layer API since it's the Google-recommended approach and I think it provides a slightly better user experience in because it doesn't require an active connection between the watch and the phone at the time of authentication. That approach is definitely not set in stone though, it's just what I went with for this initial POC. Don't hesitate to comment on that PR with any further thoughts you have.

> I see that horologist has a not-yet-documented Auth Data library, so I started a discussion there as well. Their opinions will probably be valuable: https://github.com/google/horologist/issues/1036

👍 Thanks for opening up that issue. I'll be keeping an eye on that as well.

> On my Galaxy Watch 5 (containing the fastest processor in any Wear OS watch on the market), scrolling performance is terrible with a debugProd build, even on the short top-level menu when you're not logged in.... Is the scrolling performance good in release mode, or does it need improvement there as well?

The performance is just as terrible on release builds when testing on an actual device 😞  (the watch emulator hides any performance issues).

I haven't had a chance to look into this at all yet, so I don't know what is causing the poor performance, but it is definitely a problem.

> When I tried to build a release build, the Gradle task processReleaseGoogleServices errors out...

That's because you're using [the fallback google-services.json file](https://github.com/Automattic/pocket-casts-android/blob/add/wear/wear/google-services.json_debug-only), which only covers the debug builds. When anyone tries to build the project without the actual `google-services.json` file, [that fallback file gets copied to `wear/google-services.json`](https://github.com/Automattic/pocket-casts-android/blob/add/wear/wear/build.gradle#L114-L129) because and used for debug builds.

I think you may be able to create a release build if you add an `applicationIdSuffix` of ".debug" for release builds [like debug builds have](https://github.com/Automattic/pocket-casts-android/blob/add/wear/wear/build.gradle#L29) though. Firebase probably won't work, but I don't think that will have any effect on the watch app that would prevent you from testing performance.

**Comment by mchowning** [comment]
We now have a [project issue](https://github.com/Automattic/pocket-casts-android/issues/825) tracking our progress toward an initial release of a watch app. 🎉  If you'd like to contribute, please take a look. 😄

**Comment by samueljim** [comment]
https://9to5google.com/2023/03/09/pocket-casts-wear-os-development/

We made the news 😂

**Comment by mchowning** [comment]
We're planning to start doing some open testing in a week or so. 😉

**Comment by mchowning** [comment]
>  I'd like to know why you think it is necessary to force logging in. :)

👋 @erebion! There are a few reasons. I figure most users would want to have their playback progress, subscriptions, etc. synced between their watch and their phone. Also, since we just have independent watch playback now, and that's only a Plus feature, that requires login to verify if the user is a Plus user. Once we add the ability to control the phone app from the watch (https://github.com/Automattic/pocket-casts-android/issues/1096), which will be available for free users, then we'll revisit whether it still makes sense to still require login.

**Comment by mchowning** [comment]
Closing this since our wear app has been released. There are still improvements to be made (most notably [enabling free users to use our watch app to control playback in Pocket Casts on their paired phone](https://github.com/Automattic/pocket-casts-android/issues/1096)), but we can track that work in other issues.
