### ISSUE TITLE
Sentry issue - ForegroundServiceStartNotAllowedException

### ISSUE THREAD

**Issue by Ferdev** [Automattic/pocket-casts-android#532]
### Description

There's been 248k of these errors in Sentry coming from the Android app in the last month:

[sentry.io/organizations/a8c/issues/3627837547/?environment=production&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d](https://sentry.io/organizations/a8c/issues/3627837547/?environment=production&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=14d)

We should try to get rid of this problem as it makes it difficult to spot more infrequent errors.

Some info I've found about the problem: [developer.android.com/about/versions/12/behavior-changes-12#foreground-service-launch-restrictions](https://developer.android.com/about/versions/12/behavior-changes-12#foreground-service-launch-restrictions)

Maybe related to this issues: https://github.com/Automattic/pocket-casts-android/issues/29, https://github.com/Automattic/pocket-casts-android/issues/161

### Step-by-step reproduction instructions

I don't have a list of steps to reproduce the problem.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by mchowning** [comment]
👋 @Ferdev ! Thanks for visiting the Andorid side of things! 😄 

I do think this is a duplicate of #29 . This is an issue that we've known about ever since we started targeting Android 12. It appears to be an issue coming from the Android OS itself, and I haven't been able to figure out a way to work around it.

I'm inclined to close this in favor of #29, but what do you think?

**Comment by Ferdev** [comment]
Thanks for the update @mchowning!! Definitely, agree with you, let's close this one in favor of #29 :+1:
