### ISSUE TITLE
Sentry issue - CursorWindowAllocationException

### ISSUE THREAD

**Issue by Ferdev** [Automattic/pocket-casts-android#539]
### Description

We've received 8.6k of these from the Android app during the last 30 days:

https://sentry.io/organizations/a8c/issues/3632145749/?environment=production&query=is%3Aunresolved&referrer=issue-stream&sort=freq&statsPeriod=7d

Looks like some kind of problem with cursors in the Android database.

This [other issue](https://github.com/Automattic/pocket-casts-android/issues/138) may be related.

### Step-by-step reproduction instructions

Please check the Sentry issue for more info.

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by mchowning** [comment]
The issue linked in the description no longer exists on Sentry (probably because we lost some older items when we exceeded our Sentry quota), but if I search for any `CursorWindowAllocationException`s now (like [this](https://a8c.sentry.io/issues/?project=6711064&query=is%3Aunresolved+cursorwindowallocationexception&referrer=issue-list&statsPeriod=30d)), I only see 40 events in the last 30 days. That seems like enough of a reduction from the 8.6k reported in the issue description that we can close this.
