### ISSUE TITLE
Question: Should artist be made clickable from the Player like in the Episode view

### ISSUE THREAD

**Issue by jamie23** [Automattic/pocket-casts-android#585]
### Description:
When viewing the current episode playing, in portrait mode you can see the podcast title below episode title:

![Player1](https://user-images.githubusercontent.com/1049216/202048296-672ab16f-7841-4fce-b920-25384f5703ac.png)

And in the episode view, a similar UI is used except the chevron is to the right of the title and more importantly, the title is clickable to take you to the podcast itself:

![Episode1](https://user-images.githubusercontent.com/1049216/202048349-da2631fa-8eac-4973-9ef0-59144f862c21.png)

I really like this functionality and would love it to also be in the player view, I realise you can click the shelf icon to access the go to podcast button button but just wanted to see how people thought about mimicking the UI in the podcast view to have the title of the podcast clickable like so:

![Player2](https://user-images.githubusercontent.com/1049216/202048359-f864693c-ca89-4e8e-8135-4137aea20e75.png)

**Comment by geekygecko** [comment]
I believe we did try this in the past but it was too easy to tap the progress bar and lose where your playback progress was at. We thought the extra tap into the shelf was worth it rather than the risk of losing your position.

Not that I'm stopping somebody if they want to try it out to see if they can make it work.

**Comment by mchowning** [comment]
> I really like this functionality and would love it to also be in the player view, I realise you can click the shelf icon to access the go to podcast button button

FWIW, I like to have it easier to go to the podcast page too, and I didn't know for a long time that you can actually edit which options show by default on the shelf at the bottom of the full screen player. I now have edited the default options (tapping on the three dots overflow icon, then tapping on the pencil icon is where you do this) so that the go-to-podcast option is one of the always-displayed options. I find that makes a big difference for me.

![Screen Shot 2022-11-16 at 12 04 09 PM](https://user-images.githubusercontent.com/4656348/202246448-5122a57a-a7d2-466a-b134-5728f5121424.png)

**Comment by jamie23** [comment]
> It was too easy to tap the progress bar and lose where your playback progress was at. We thought the extra tap into the shelf was worth it rather than the risk of losing your position.

I suspected there must be a reason that it's a menu item rather than being clickable 😄. That makes complete sense, I didn't have much issue when I was testing it after quickly implementing the behaviour but I realise that I'm testing this at a desk and not on the move trying to use the app.

> FWIW, I like to have it easier to go to the podcast page too, and I didn't know for a long time that you can actually edit which options show by default on the shelf at the bottom of the full screen player.

Awesome! I didn't realise this functionality existed so I've now added it to my default shelf, thank you! 

Would you like me to close this issue or keep it open for further conversation?

**Comment by mchowning** [comment]
I'm glad that helped. 😄 

> Would you like me to close this issue or keep it open for further conversation?

If you feel like this has resolved the issue of making it easier for you to access the podcast page from the full screen player, let's go ahead and close this.
