### ISSUE TITLE
Feature: Add labels to each episode

### ISSUE THREAD

**Issue by alexstine** [Automattic/pocket-casts-android#750]
### What problem does this address?

If I open a podcast and explore my list of episodes, there is not enough meta information telling me the status of the episode. For example, it would be nice to know if the episode was queued for up next, currently playing, the time remaining if it is currently playing, and some type of generic status to say unplayed but not added to up next queue.

### What is your proposed solution?

Add the suggested meta information to make it clear for the user what the state of the episode is.

### Did you search for existing feature suggestions?

- [X] I have searched for existing feature suggestions.

**Comment by CookieyedCodes** [comment]
Ummmm dosen't the app currently do this? Can you provide a screenshot of where your asking for such information because it's a tad unclear which page your requesting need more info😅 ![Screenshot_2023-02-03-08-55-18-81_28ad70af3b47247953fcd94176b9a9c1.jpg](https://user-images.githubusercontent.com/20846898/216555714-812096c0-52cc-403c-a78e-0d5c0c98f3d8.jpg)

**Comment by alexstine** [comment]
@CookieyedCodes Okay, I see where it says the time remaining now but it still does not tell me if the episode is queued to play next. It may show it visually but using TalkBack accessibility feature as a blind person, it does not read such information.

Thanks.

**Comment by CookieyedCodes** [comment]
@alexstine Oh fair enough, didn't understand about your usecase,  it's the blue icon for upnext (& a green check box for downloaded, they are visual icons not interactive icons so that's probably not included under talk back -checked their not-

hmmmm I might have a solution tho, if you set your row action to download instead of played (profile>settings gear>general>row action) the play icon at the end of the episode list will become a downloaded icon, once the episode is actually downloaded it will actually become a play icon and announce it as so you would know thats ready for upnext (the moment you hit play it plays that file immediately as you would expect & move the old playing file to upnext)

All your downloads will also appear under profile>downloads so that might help you 🤔

I do wonder could the devs can improve this accessibility for you though 🤔

**Comment by alexstine** [comment]
Would be nice to have devs improve this. I do not like to download my episodes, I just stream them as I wish. Makes sense, the icons need some type of TalkBack interpretable text.

https://developer.android.com/guide/topics/ui/accessibility/principles

I do not know how to code in these languages but maybe this is easy enough for me to learn. Generally stick to web dev JS/PHP.
