### ISSUE TITLE
Sleeptimer not working

### ISSUE THREAD

**Issue by mbaumeyer** [Automattic/pocket-casts-android#802]
### Description

Hi
Since one of the last updates, the sleep timer no longer works for me (Zenfone 8, Android 13). The episodes just keep running and the playback only stops when they are finished or the screen is activated.

The app has all permissions and in other apps (Spotify, Smart AudioBook Player) the sleep timer works fine.

Can anyone help here?

### Step-by-step reproduction instructions

Set sleep timer

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Asus Zenfone 8, Android 13, AppVer: 7.32

**Comment by mchowning** [comment]
👋 @mbaumeyer ! Sorry to hear that. 

Could you reach out to support from within the app (Profile tab → ⚙️ → `Help & Feedback` → `Get in touch` →`Get Support`)? By doing that, we'll have a much better chance to figure out what is going on because we'll get logs from the app. When you reach out, it would also be helpful if you could let us know the times when the sleep timer failed to work so we know where to look in your logs.

Also, if you updated to Android 13 around the time the sleep timer stopped working, please let us know that too. I doubt that would cause the sleep timer not to work, but it's still helpful information for us to know.

**Comment by mbaumeyer** [comment]
Thanks. Will do.

**Comment by mchowning** [comment]
Did this get resolved for you @mbaumeyer ?

**Comment by mbaumeyer** [comment]
Yeah, at some point it worked again. I had contacted the support but never got an answer. Unfortunately, I can't really remember what caused it.

**Comment by mchowning** [comment]
Glad to hear it's working now. I'll go ahead and close this issue then, but if the issue comes back, feel free to reopen this or open a new issue.
