### ISSUE TITLE
I got a lot of errors about ANR.

### ISSUE THREAD

**Issue by aab11bcc2233** [Automattic/pocket-casts-android#823]
### Description

The app(version: 7.34-rc-1) isn't responding on my device(Xiaomi 10s, Android 13), but it's working on the other device(Samsung Galaxy S8, Android 9). Maybe there is something wrong with Xiaomi's ROM?

### Step-by-step reproduction instructions

1. open the app.

### Screenshots or screen recording

https://user-images.githubusercontent.com/5644311/223662352-16ecbfdb-4ccf-4a20-8a40-4905d83c1681.mp4

![WechatIMG93](https://user-images.githubusercontent.com/5644311/223662414-e41d72f6-55a7-4c7a-bff3-96c55775e5b1.jpeg)

[anr_2023-03-08-11-42-52-526.txt](https://github.com/Automattic/pocket-casts-android/files/10918726/anr_2023-03-08-11-42-52-526.txt)

[anr_2023-03-08-11-24-48-898.txt](https://github.com/Automattic/pocket-casts-android/files/10918731/anr_2023-03-08-11-24-48-898.txt)

[anr_2023-03-08-11-51-54-850.txt](https://github.com/Automattic/pocket-casts-android/files/10918735/anr_2023-03-08-11-51-54-850.txt)

[anr_2023-03-08-12-02-57-687.txt](https://github.com/Automattic/pocket-casts-android/files/10918738/anr_2023-03-08-12-02-57-687.txt)

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

**Comment by mchowning** [comment]
👋 @aab11bcc2233 . Thanks for reaching out, and I'm sorry the app is misbehaving like that. I don't think there were any changes in 7.34 that would cause this kind of issue. 🤔  I assume the app worked fine until you updated from 7.33 to 7.34? 

If you haven't yet, please try restarting your device just to ensure there's not some temporary state messing things up. 

Assuming that doesn't work (and I'll be surprised if it does), could you reach out to support from within the app on your Xiaomi device (Profile tab → ⚙️ → Help & Feedback → Get in touch →Get Support)? By doing that, we'll have a much better chance to figure out what is going on because we'll get logs from the app.
