### ISSUE TITLE
Bug: background update ignores download preferences when upnext is set to queue new episodes

### ISSUE THREAD

**Issue by gyund** [Automattic/pocket-casts-android#839]
### Description

https://github.com/Automattic/pocket-casts-android/blob/b1946883673f38d38d8590fecb5d15d4312d069a/modules/services/repositories/src/main/java/au/com/shiftyjelly/pocketcasts/repositories/refresh/RefreshPodcastsTask.kt#L64

In the line above, the constraints specify the background task should be run when `NetworkType.CONNECTED` but it should probably be conditional based on the user preferences for preferring downloads on an UNMETERED connection. The setting should probably not be statically set to `NetworkType.CONNECTED` but should be conditional and alternatively set to `NetworkType.UNMETERED`.

I suspect what is happening is that the task runs every hour in the background and queues the podcast into the upnext queue. The download may/may-not be deferred until the player requests it to be played....which might be what eventually triggers the download.

Having the task mirror the download preferences would prevent the scheduling from triggering the update and enqueing any episodes in the up next queue.

I noticed a high foreground usage of data with daily pocketcasts which led me to look into this.

#### Settings

- Auto Download 
    - only on unmetered wifi (on)
    - episodes added to up next (on)  

### Expected Behavior 

Downloads will be delayed until connected to an unmetered connection and episodes won't be queued into the upnext queue until attached to an unmetered connection.

### Actual Behavior 

Downloads are happening on metered wifi

### Version Observed on

7.33 (9077)

**Comment by mchowning** [comment]
👋  @gyund ! Thanks for reporting this.

Just so I understand better, is the problem that you don't want episodes to be added to the up next queue when on a metered connection because playing them before getting back on an unmetered connection results in data usage, or are you seeing downloads happening on metered connections that should not be occurring?

> I noticed a high foreground usage of data with daily pocketcasts which led me to look into this.

Do you have the setting `Storage & Data use` → `Warn before using data` turned on? That should help you avoid unexpectedly using data.

**Comment by gyund** [comment]
Yes the warn before data was turned on as well but the download would still occur on metered data. What seemed to be happening is that if you have up next queue to the top, the hourly update from work manager would still queue new podcasts to the queue. I couldn't confirm if it actually downloaded at the same time. I suspect not. However once in the queue, it can now be played. Podcasts that queue on the bottom don't typically have this issue as you usually have enough podcasts in the queue to get home, for example, and have them downloaded by the time you need em. Daily podcasts, for example might queue in the morning while on a metered connection, but play before you get home if queued at the top...triggering the download. I created a MR  #842 with fixes based on what I could tell about the mechanics stepping through the debugger. Descriptions in the MR broken up into two different change sets based on how aggressive you want to be from an app design perspective. 

The patch for the work manager would be transparent to the user because it only affects scheduling of the background task based on network connectivity. 

The other commit would basically make swiping down on the podcast page do nothing when you're on a metered connection....but that may have adverse side affects I'm not aware of yet not being a FT dev on this, but other SW stuff. So just my disclaimer 😜. Notes are in the MR with the specifics.

**Comment by gyund** [comment]
Initially I suspected 2 but after you confirmed in the MR #842 the downloadmanager check and looking at the description of 1 a bit closer, it's probably the Android auto issue already described in the setting. 

![Screenshot_20230329-215510](https://user-images.githubusercontent.com/12544461/228708208-b1254990-5696-4d4b-bfcd-6fe313183563.png)

I suspect the description describes exactly what happens. It streams but doesn't download but updates of the feeds on metered networks trigger it being added to the up next queue. TBD if #842 is the right fix by preventing background updates.

**Comment by mchowning** [comment]
So if the warning dialog worked on Android Auto, it sounds like that would address your problem. Is that right?

I wasn't involved in the decision to not show that warning in Android Auto, but I strongly suspect that it had to do with minimizing driver distraction. If we did show the warning, and a user didn't want to stream, then they would have to tap something on the warning, pull up their up next queue, identify an already-downloaded episode, and then start playing that, which seems like way too much interaction to require from someone driving.

I'm trying to think of other ways we could address this issue. If Android Auto had a setting where it would always load the next downloaded episode from the up next queue, would that address the problem for you? Or maybe something like a setting that made the up next queue in Android Auto only include downloaded episodes could work? 🤔 The tricky part there would just be making it clear to the user why they have different up next queues on different devices since one of the main benefits of the up next queue system that Pocket Casts uses is the simplicity of having the same queue across all your devices.

**Comment by gyund** [comment]
Fyi, here's a screenshot confirming what happens in the up next queue with all the options mentioned above to warn when using background data and auto download only on unmetered wifi.

![Screenshot_20230412-122329.png](https://user-images.githubusercontent.com/12544461/231521571-7bbe3895-1a1c-4244-b48d-6bb7c8260850.png)

The refresh will add it to the up next queue but it won't be downloaded (no checkmark) until it's scheduled to play. Then it'll stream and download. 🤷

The combination of both warn when using data and download only on wifi are misleading because both allow downloads. 

Perhaps if both are set, the user has indicated  more strongly they'd like to avoid downloads...and maybe then a refresh should not occur either as that is itself a download. Could also add an option for "really, don't update unless on unmetered wifi" 😜. Or maybe just switch the option under background refresh to a "sync on wifi only" to avoid the confusion of a warning in your pocket ⚠️.

**Comment by gyund** [comment]
See https://github.com/Automattic/pocket-casts-android/issues/858#issuecomment-1506072099 for info about a tackling this in combination with another issue.

**Comment by InsertUser** [comment]
I find "warn before using data" mostly useless as it is typically warning the inside of my pocket while I'm driving due to the add before downloaded behaviour. Can we have a setting that evaluates earlier in the logic for "automatically skip to next downloaded in Up Next if next episode(s) hasn't finished downloading"? That way the "warn before using data" setting would only really apply when starting playback manually.

**Comment by gyund** [comment]
> I find "warn before using data" mostly useless as it is typically warning the inside of my pocket while I'm driving due to the add before downloaded behaviour. Can we have a setting that evaluates earlier in the logic for "automatically skip to next downloaded in Up Next if next episode(s) hasn't finished downloading"? That way the "warn before using data" setting would only really apply when starting playback manually.

Thanks @InsertUser,  I was having [a chat](https://github.com/Automattic/pocket-casts-android/issues/858#issuecomment-1506148976) with @mchowning a bit about this where I argued a similar point. I thought it was just to mask a bug, but it may serve another purpose involving synchronization between the app and web.

The change I'm making on PR #885 should actually prevent the issue you're describing from happening because you would only download and queue new episodes while you were on wifi for example, and there wouldn't be any background updates or automatic updates just from opening the app while you were on the road on metered data that could trigger undownloaded podcasts to be added to the up-next queue...the case requiring the "warning". You can still swipe down to refresh manually though. It'll be an "advanced" option so they can evaluate usage and metrics, but it may eventually graduate 👨‍🎓 to a full-fledged option after further evaluation if it seems to make more sense. 🤷 

The main issue with simply skipping is how the up-next queue would work. There's not really a spot for skipped items to go without introducing complex logic...and there is a lot of logic I'm finding out😄. 

_Note: I'm a FT software developer, but not for Automattic. I jump around a lot between different languages based on whatever software issue I'm working on._ 

In the short term, if you hold the app icon and go into the android app settings for pocket-cast, [toggle the switch](https://github.com/Automattic/pocket-casts-android/issues/839#issuecomment-1502098241) to disable background data and that will eliminate the need for the "Warning", as long as you don't open the app directly on the road and go through android automotive or auto via the google maps interface.

**Comment by InsertUser** [comment]
@gyund Does that change delay the action to  'add to Up Next' to after download completes? If not I think there is a risk that getting to a partially completed download could trigger a data use warning when it tries to play? This is most likely with 'timely' podcasts that you generally want to go into the play next slot rather than added to the end of the list.

I think the delayed add behaviour was the default until the redesign a few years back and before that I don't think I had this issue.

**Comment by gyund** [comment]
> @gyund Does that change delay the action to  'add to Up Next' to after download completes? If not I think there is a risk that getting to a partially completed download could trigger a data use warning when it tries to play? This is most likely with 'timely' podcasts that you generally want to go into the play next slot rather than added to the end of the list.
> 
> I think the delayed add behaviour was the default until the redesign a few years back and before that I don't think I had this issue.

@InsertUser It actually leverages android workmanager constraints to prevent the app from getting the information to begin with on metered networks, so there's no split brain logic to keep track of. Same deal on app open but different mechanism.
