### ISSUE TITLE
Speed control stops at 2x on media notification

### ISSUE THREAD

**Issue by eamodio** [Automattic/pocket-casts-android#964]
### Description

On the media notification tapping the speed button loops through the speed settings, but stops at 2x. I often use between 2x and 3x and it's frustrating to not be able to control that from the notification, especially if I fat finger it and I have to go back to the app to fix it. 

### Step-by-step reproduction instructions

1. Tap on the speed setting on the media notification
2. Observe that it loops at 2x rather than 3x

### Did you search for existing bug reports?

- [X] I have searched for existing bug reports.

### Device, Operating system, and Pocket Casts app version

Google Pixel 7 Pro with Android 13

**Comment by EnigmaSolved** [comment]
I also would like to see this improved. :)

**Comment by mebarbosa** [comment]
Apologies for the frustration! We'll address this request in the upcoming `7.59` version. Thanks for your patience!

**Comment by EnigmaSolved** [comment]
Thank you so much @mebarbosa !! One thing though (there's always one more thing, isn't there? 😆), it would be really helpful to eventually have granularity between `2x` and `3x`, ie, `2.2x`, `2.4x`, `2.6x`, `2.8x`. There is a high probability that others will be requesting this as well in relation to the very helpful improvements you have made in #1862 so I figured I would lead the way. :) 

Part of the thing is that when we get up to `2x` and higher the fine granularity is really helpful -- there is a _big_ difference between `2x` and `3x`, so I doubt that many people want to jump straight from `2` to `3`, but rather probably want to increment a little a time. I know for myself that I often have to adjust up/down a little for different podcasts, depending on who is being interviewed and how well I can understand them at higher speeds. I actually think that when you get above `2x` there is a case to be made for incrementing by `.1x` instead of `.2x` because of the need for finer control at such high speeds (ie, `2.1x`, `2.2x`, `2.3x` and so on).

Just some things to consider for a future update. Thank you again for your hard work! :)
